### ISSUE TITLE
Secondary Subs Not Loading

### ISSUE THREAD

**Issue by nickstack** [gmertes/NflxMultiSubs#20]
Just started having this issue today. Seconary subs section is blank. 

NflxMultiSubs> Fatal:  TypeError: Cannot read properties of undefined (reading 'downloadUrls')

Can you look into this? Thanks

**Comment by GangstaXavi** [comment]
same here, the console showed this:
btw im using version 2.2.8 on win 10 with chrome version 98.0.4758.102 (Official Build) (arm64)

nflxmultisubs.min.js:2 NflxMultiSubs> Fatal:  TypeError: Cannot read properties of undefined (reading 'downloadUrls')
    at Function._buildImageBased (chrome-extension://jepfhfjlkgobooomdgpcjikalfpcldmm/nflxmultisubs.min.js:2:102918)
    at Function.build (chrome-extension://jepfhfjlkgobooomdgpcjikalfpcldmm/nflxmultisubs.min.js:2:102537)
    at chrome-extension://jepfhfjlkgobooomdgpcjikalfpcldmm/nflxmultisubs.min.js:2:113419
    at Array.map (<anonymous>)
    at chrome-extension://jepfhfjlkgobooomdgpcjikalfpcldmm/nflxmultisubs.min.js:2:113409
    at chrome-extension://jepfhfjlkgobooomdgpcjikalfpcldmm/nflxmultisubs.min.js:2:113441

**Comment by sh-cho** [comment]
Same here 🥲

**Comment by gmertes** [comment]
Thanks for the reports everyone! Fixed and pushed v2.2.9 to the store. I'll leave this issue open until it is approved (also you can let me know if the fix works for you when it's up).

**Comment by sh-cho** [comment]
@WingCH Hi, can you follow up this on safari extension?

**Comment by WingCH** [comment]
Thanks for your reminder
I have uploaded the new version to apple, waiting for review

**Comment by gmertes** [comment]
v2.2.9 is published on the Chrome and Firefox stores. 🥰 Does it work for everyone now?

**Comment by WingCH** [comment]
mac version already pass review and deployed in mac app store!

**Comment by sh-cho** [comment]
I checked both safari, chrome extension and they works well :)
